name: PowerShell Demo

on: [push]

jobs:
  ps-job:
    runs-on: windows-latest

    steps:
      - name: PowerShell Basic Commands
        shell: pwsh
        run: |
          Get-Location
          Get-ChildItem
          Write-Host "Hello from PowerShell"
